# debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  datasource:
#    url: "jdbc:h2:mem:testdb"


---
# persistence
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/social-media-database
    username: social-media-user
    password: dummypassword
---
# security
spring:
  security:
    user:
      name: username
      password: password






#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        ddl-auto: update

#spring:
#  jpa:
#    defer-datasource-initialization: true
#    show-sql: true