version: '3.7'

services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "--spring.profiles.active=dev"
    networks:
      backend:
        aliases:
          - "licenseservice"
networks:
  backend:
    driver: bridge
    
  