spring:
  application:
    name: api-gateway

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id : my-route
#          uri : lb://currency-exchange
#          predicates:
#            - Path=/currency-exchange/**
server:
  port: 8765
# Eureka naming server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#debug: true
#trace: true
---
#Observability
management:
  tracing:
    sampling:
      probability: 1.0
---
# Logging format
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
