spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


server:
  port: 8765
# Eureka naming server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#debug: true
trace: true
