spring:
  application:
    name: spring-cloud-config-server

server:
  port: 8888

---
#config server
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///home/juanfe/develop/git-localconfig-repo