spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-conversion
server:
  port: 8100

# Eureka naming server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

