# configuration server
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange
server:
  port: 8000
---
# database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    defer-datasource-initialization: true
---
#actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
---
# log
#logging:
#  level:
#    io.github.resilience4j.circuitbreaker: DEBUG




---
# Eureka naming server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
#Resilience4j
#circuit breaker
resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
  ratelimiter:
    instances:
      default:
        limitForPeriod: 1
        limitRefreshPeriod: 10s
        registerHealthIndicator: true
      simple-api1:
        limitForPeriod: 1
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      sample-api:
        maxConcurrentCalls: 10
---
#Observability
management:
  tracing:
    sampling:
      probability: 1.0
---
# Logging format
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
