spring:
  profiles:
    active:
      - dev
---

spring:
  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: limits-service

  cloud:
    config:
      profile: qa
limits-service:
  minimum: 1
  maximum: 6666
  source: classpath
#loggig
logging:
  level:
    web: DEBUG
---
#spring:
#  profiles:
#    include:
#      - dev
#limits-service:
#  minimum: 1
#  maximum: 6666




