
---

spring:
  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: limits-service
limits-service:
  minimum: 1
  maximum: 6666
#loggig
logging:
  level:
    web: DEBUG
---
#spring:
#  profiles:
#    include:
#      - dev
#limits-service:
#  minimum: 1
#  maximum: 6666




